### ISSUE TITLE
attention_store中一直为空

### ISSUE THREAD

**Issue by DaiZhewei** [xiaotianqing/InstDiffEdit#1]
在运行sample_use.py时报错提示"..../InstDiffEdit/model/sample_use.py", line 273, in <module>
    main(args)
KeyError: 'up_cross'
报错提示键值为空，调试时发现attentionstore中键值一直为空，想问下这个问题应该如何解决呀？感谢！

**Comment by SiyuanHe0826** [comment]
在别的模型中也遇到这个问题了，蹲一个解答

**Comment by xiaotianqing** [comment]
请问下您使用的diffusers的版本是多少，我的环境下diffuser为0.8.0版本，您可以试试
